language: ruby
os: linux
dist: trusty
sudo: required
rvm: 2.3.7

before_script:
  - gem install rubocop

script:
  - rubocop
  - ./install --force-curl
  - ./uninstall -f || true
  - sudo rm -rf /home/linuxbrew/.linuxbrew
  - ./install.sh
  - /home/linuxbrew/.linuxbrew/bin/brew install ack
  - ./uninstall -f || true

branches:
  only:
    - master
